server:
  error:
    include-message: always
    include-binding-errors: always
#  port: 8080
#  servlet:
#    context-path: /SpringBootRepository

spring:
#  main:
#    web-application-type: none
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/exam_management
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
          new_generator_mappings: true
        format_sql: true
        hb2dll:
          auto: update
    show-sql: true
    generate-ddl: true
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      enabled: true

# App Properties
#bezkoder:
#  app:
#    jwtSecret: bezKoderSecretKey
#    jwtExpirationMs: 86400000

app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ
